version: '3.7'

services:
  tornado:
    build: .
    restart: always
    ports:
      - ${TORNADO_PORT}:8888
    env_file:
      - .env
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data/db:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
